name: Build and Test Docker Compose Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Cambiar a ubuntu-24.04 para ser más específico

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose  # Paso adicional para instalar Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verifica la instalación de Docker Compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3  # Actualizado a la versión v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d  # Asegúrate de que el docker-compose.yml esté en la raíz

    - name: Wait for services to be ready
      run: |
        docker-compose exec task_server /bin/sh -c "until nc -z localhost 5024; do sleep 1; done"  # Asegura que el servicio esté listo

    - name: Test application
      run: |
        docker-compose exec task_server npm run test  # O el comando que uses para probar tu app

    - name: Stop Docker Compose services
      run: |
        docker-compose down
